version: '3.9'

services:
  app:
    build: .
    container_name: blockchain
    ports:
      - 4000:4000
    volumes:
      - ./src:/usr/share/app
    networks:
      - node

networks:
  node:
    name: nodejs